name: Write raw machine data to InfluxDB 3.0
language: python
variables:
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: Host address for the InfluxDB instance.
    defaultValue: https://us-east-1-1.aws.cloud2.influxdata.com
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: Authentication token to access InfluxDB.
    defaultValue: influx_db3
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: Organization name in InfluxDB.
    defaultValue: ContentSquad
    required: false
  - name: INFLUXDB_DATABASE
    inputType: FreeText
    description: Database name in InfluxDB where data should be stored.
    defaultValue: machine-generator-data
    required: true
  - name: INFLUXDB_TAG_COLUMNS
    inputType: FreeText
    description: Columns to be used as tags when writing data to InfluxDB.
    defaultValue: "['tag1', 'tag2']"
    required: false
  - name: INFLUXDB_MEASUREMENT_NAME
    inputType: FreeText
    description: The InfluxDB measurement to write data to. If not specified, the name of the input topic will be used
    defaultValue: machine-health
    required: false
  - name: INFLUXDB_FIELD_KEYS
    inputType: FreeText
    description: The fields to include when writing the measurement data
    defaultValue: "['field1','field2']"
    required: true
  - name: BROKER_ADDRESS
    inputType: FreeText
    description: ''
    defaultValue: publickafka.quix.io
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
